post http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Fred",
  "email": "fred@fred.com",
  "password": "password",
  "password_confirmation": "password"
}

###
post http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "fred@fred.com",
  "password": "password"
}


###
get http://localhost:3000/events.json



###
post http://localhost:3000/events.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2MjQwNzR9.-dgyT-uymk2KOVFQg_DwummElFgyt31TESpbY1tUEvQ

{
  "sport_id": 1,
  "location_id": 1,
  "year": 2022,
  "month": 8,
  "day": 26,
  "hour": 17,
  "minute": 15
}

###
post http://localhost:3000/event_participants.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2MjQwNzR9.-dgyT-uymk2KOVFQg_DwummElFgyt31TESpbY1tUEvQ

{
  "event_id": 1
}