post http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Joe",
  "email": "joe@joe.com",
  "password": "password",
  "password_confirmation": "password"
}

###
post http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "joe@joe.com",
  "password": "password"
}


###




###
post http://localhost:3000/events.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2MjQwNzR9.-dgyT-uymk2KOVFQg_DwummElFgyt31TESpbY1tUEvQ

{
  "sport_id": 1,
  "location_id": 1,

}

###